# TODO: these containers are running as root, I should probably change that...
# Documentation on docker compose https://docs.docker.com/compose/compose-file/
services:
  # Define the Flask Backend container, name on the network is "api"
  api:
    # Defines how to build the container
    build:
      context: .
      dockerfile: Dockerfile.flask
    image: ghcr.io/reelgoodosu/flask
    # Bind the volume with the python script to the container, so we can make changes on the fly
    volumes:
      - type: bind
        source: ./api
        target: /app
    # Must wait for the volume to bind before executing the script
    working_dir: /app
    entrypoint: [ "bash", "-c", "sleep 1 && ./app.py" ]
  # Container for react frontend
  client:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: ghcr.io/reelgoodosu/react
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    entrypoint: [ "bash", "-c", "sleep 1 && npm start" ]
    ports:
      - "3000:3000"